### ISSUE TITLE
bowtie2 revision changeset

### ISSUE THREAD

**Issue by drosofff** [ARTbio/metavisitor#17]
@ccedmendoza there is two revision changesets findable in the repo (using the search tool):
- 97d1923c8c4b
- dc1639b66f12

but only one installed with the toollist.yml.
And I think that the version installed by ansible or docker, strangely enough, is not the same. But I am not sure.

**Comment by ccedmendoza** [comment]
I think we can close this issue. I only find one revision of each tool
